
CXX		= $(JUMBOLAIYA_CXX)
LD              = g++
LDFLAGS         += -Wl,-rpath,$(JUMBOLAIYA_BASEDIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O3 -std=c++11 -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = g++
SOFLAGS         = -g -fPIC -shared

ifeq ($(JUMBOLAIYA_OPENCV),1)
CXXFLAGS += -DUSE_OPENCV
endif
